name: Build and Publish sfpowerscripts Docker Image to ghcr


on:
  workflow_call:
   inputs:
    job-environment:
        type: string
        required: true
    repo:
      type: string
      required: true
    dockerFileName:
      type: string
      required: false
      default: sfp
    image:
      type: string
      required: false
      default: sfp
    suffix-tag:
      type: string
      required: true
   secrets:
      username:
          required: true
      token:
          required: true

jobs:

  build:
    name: 'build docker image'
    environment: ${{ inputs.job-environment }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write 

    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.4.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.username }}
        password: ${{ secrets.token }}


    # Extract metadata (tags, labels) for Docker
    # https://github.com/docker/metadata-action
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4.4.0
      with:
          images:  ghcr.io/${{ inputs.repo }}/${{ inputs.image }}


    - name: 'Get package version and name'
      run: |
        echo "PKG_VERSION=$(jq -r ".version" package.json)" >> $GITHUB_ENV
        RELEASE_NAME=$(jq -r ".release" package.json)
        RELEASE_NAME_AS_ARRAY=($RELEASE_NAME)
        RELEASE_NAME=$(echo ${RELEASE_NAME_AS_ARRAY[0]} | cut -c1-3)${RELEASE_NAME_AS_ARRAY[1]}
        echo "RELEASE_NAME=release-$RELEASE_NAME"  >> $GITHUB_ENV


    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
          file: dockerfiles/${{inputs.dockerFileName}}.Dockerfile
          context: dockerfiles
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
              ghcr.io/${{ inputs.repo }}/${{ inputs.image }}:${{ env.PKG_VERSION }}-${{ inputs.suffix-tag }}
          build-args: | 
                  SFPOWERSCRIPTS_VERSION=${{ env.PKG_VERSION }}
                  GIT_COMMIT=${{ github.sha}}


    - name: Sign the images with GitHub OIDC Token
      env:
         DIGEST: ${{ steps.docker_build.outputs.digest }}
         TAGS:  ghcr.io/${{ inputs.repo }}/${{ inputs.image }}:${{ env.PKG_VERSION }}-${{ inputs.suffix-tag }}
      run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          cosign sign --yes ${images}

   #Tag the image as develop
    - name: 'Tag Docker'
      uses: ./.github/actions/tagDocker
      with:
         repo: ${{ inputs.repo }}
         image: ${{ inputs.image }}
         existing-tag: ${{ env.PKG_VERSION }}-${{ inputs.suffix-tag }}
         new-tag: development
         registry: ghcr.io
         username:   ${{ secrets.username }}
         token: ${{ secrets.token }}


